import type { SafetyContact, SafetyLocation, Route, ServiceNotice, Report } from '../types';

export const PRIMARY_EMERGENCY: SafetyContact = {
  id: 'emergency-primary',
  label: 'Campus Security 24/7 Control Room',
  phone: '+91-11-2659-1000',
  instructions: 'Official university emergency helpline. For immediate danger, medical trauma, violence, or active fire. Never use web forms for emergencies.',
  source: 'Office of Campus Safety & Security',
  verifiedAt: '2026-10-01T08:00:00Z',
  isDemo: false,
};

export const SEED_CONTACTS: SafetyContact[] = [
  PRIMARY_EMERGENCY,
  {
    id: 'health-centre',
    label: 'Campus Health Centre & Ambulance',
    phone: '+91-11-2659-1111',
    instructions: 'On-campus primary healthcare, urgent first-aid clinic, and dedicated ambulance service.',
    source: 'Chief Medical Officer',
    verifiedAt: '2026-10-01T08:00:00Z',
    isDemo: false,
  },
  {
    id: 'counseling-support',
    label: 'Student Wellness & Counseling Desk',
    phone: '+91-11-2659-1222',
    instructions: 'Confidential psychological support, crisis counseling, and student well-being assistance.',
    source: 'Dean of Student Affairs',
    verifiedAt: '2026-10-01T08:00:00Z',
    isDemo: false,
  },
  {
    id: 'women-safety',
    label: 'Internal Committee (IC) & Women Safety Helpline',
    phone: '+91-11-2659-1333',
    instructions: 'Confidential reporting and immediate safety escort assistance for female students and staff.',
    source: 'University Gender Advisory Cell',
    verifiedAt: '2026-10-01T08:00:00Z',
    isDemo: false,
  },
];

export const SEED_LOCATIONS: SafetyLocation[] = [
  {
    id: 'loc-gate1',
    name: 'Main Gate 24/7 Security Booth',
    kind: 'SECURITY_POST',
    campusLocation: 'Gate 1, North Avenue (Opposite Administration Building)',
    description: 'Staffed around the clock by uniformed security personnel. Equipped with automated defibrillator (AED) and direct hotline to local emergency services.',
    verifiedAt: '2026-10-01T08:00:00Z',
    isDemo: false,
  },
  {
    id: 'loc-health',
    name: 'Central Health Centre & First Aid Clinic',
    kind: 'HEALTH_CLINIC',
    campusLocation: 'Medical Enclave, East Campus (Behind Faculty Housing)',
    description: 'Open 24 hours for emergency triage and trauma stabilization. Two campus ambulances stationed permanently at the ambulance bay.',
    verifiedAt: '2026-10-01T08:00:00Z',
    isDemo: false,
  },
  {
    id: 'loc-library',
    name: 'Central Library Night Safe Haven',
    kind: 'SAFE_HAVEN',
    campusLocation: 'Central Library Foyer, Ground Floor',
    description: 'Well-lit monitored perimeter with security personnel on duty until 06:00 AM. Equipped with emergency help point intercom.',
    verifiedAt: '2026-10-01T08:00:00Z',
    isDemo: false,
  },
  {
    id: 'loc-sports',
    name: 'Sports Complex Primary Assembly Point',
    kind: 'ASSEMBLY_POINT',
    campusLocation: 'Main Athletic Grounds, North Perimeter',
    description: 'Designated outdoor evacuation assembly zone for earthquake or structural emergencies affecting Academic Blocks 1-4.',
    verifiedAt: '2026-10-01T08:00:00Z',
    isDemo: false,
  },
];

export const SEED_ROUTES: Route[] = [
  {
    id: 'route-rohini-burari-sonipat',
    name: 'Delhi North: Rohini & Burari ⇄ Sonipat Campus',
    description: 'Key North Delhi commuter corridor connecting Rohini, Burari, and Mukarba Chowk with Sonipat Campus along Outer Ring Road and NH-44.',
    operatingDays: 'Monday to Saturday (Morning & Evening Services)',
    timezone: 'IST',
    lastUpdated: '2026-10-09',
    isDemo: false,
    stops: [
      { id: 'rb-s1', name: 'Rohini Sector 18 Metro Station (East Gate)', sequence: 1, campusLocation: 'Near Metro Pillar #142', morningTime: '07:30 AM', eveningTime: '06:10 PM' },
      { id: 'rb-s2', name: 'Burari Crossing Bus Stand', sequence: 2, campusLocation: 'Outer Ring Road Flyover Bay', morningTime: '07:48 AM', eveningTime: '05:48 PM' },
      { id: 'rb-s3', name: 'Mukarba Chowk Transport Interchange', sequence: 3, campusLocation: 'GT Karnal Road Stoppage', morningTime: '08:05 AM', eveningTime: '05:28 PM' },
      { id: 'rb-s4', name: 'Alipur Main Highway Shelter', sequence: 4, campusLocation: 'Opposite Alipur Police Post', morningTime: '08:22 AM', eveningTime: '05:08 PM' },
      { id: 'rb-s5', name: 'Kundli Border / KMP Expressway Junction', sequence: 5, campusLocation: 'Toll Plaza Commuter Point', morningTime: '08:42 AM', eveningTime: '04:48 PM' },
      { id: 'rb-s6', name: 'Sonipat Campus Main Terminal', sequence: 6, campusLocation: 'Academic Quadrangle Bus Bay', morningTime: '09:00 AM', eveningTime: '04:30 PM' },
    ],
    scheduledDepartures: ['07:30 AM', '04:30 PM'],
    morningSchedule: [
      { stopName: 'Rohini Sector 18 Metro Station', time: '07:30 AM', location: 'Near Metro Pillar #142' },
      { stopName: 'Burari Crossing Bus Stand', time: '07:48 AM', location: 'Outer Ring Road Flyover Bay' },
      { stopName: 'Mukarba Chowk Transport Interchange', time: '08:05 AM', location: 'GT Karnal Road Stoppage' },
      { stopName: 'Alipur Main Highway Shelter', time: '08:22 AM', location: 'Opposite Alipur Police Post' },
      { stopName: 'Kundli Border / KMP Junction', time: '08:42 AM', location: 'Toll Plaza Commuter Point' },
      { stopName: 'Sonipat Campus Main Terminal', time: '09:00 AM', location: 'Academic Quadrangle Bus Bay (Arrival)' },
    ],
    eveningSchedule: [
      { stopName: 'Sonipat Campus Main Terminal', time: '04:30 PM', location: 'Academic Quadrangle Bus Bay (Departure)' },
      { stopName: 'Kundli Border / KMP Junction', time: '04:48 PM', location: 'Toll Plaza Commuter Point' },
      { stopName: 'Alipur Main Highway Shelter', time: '05:08 PM', location: 'Opposite Alipur Police Post' },
      { stopName: 'Mukarba Chowk Transport Interchange', time: '05:28 PM', location: 'GT Karnal Road Stoppage' },
      { stopName: 'Burari Crossing Bus Stand', time: '05:48 PM', location: 'Outer Ring Road Flyover Bay' },
      { stopName: 'Rohini Sector 18 Metro Station', time: '06:10 PM', location: 'Near Metro Pillar #142 (Last Drop)' },
    ],
  },
  {
    id: 'route-manglapuri-sonipat',
    name: 'Delhi West: Manglapuri ⇄ Sonipat Campus',
    description: 'Serves South-West and West Delhi commuters traveling between Manglapuri, Janakpuri, Punjabi Bagh, and Sonipat Campus.',
    operatingDays: 'Monday to Saturday (Morning & Evening Services)',
    timezone: 'IST',
    lastUpdated: '2026-10-09',
    isDemo: false,
    stops: [
      { id: 'mp-s1', name: 'Manglapuri Bus Terminal (Dwarka / Janakpuri)', sequence: 1, campusLocation: 'Terminal Bay 3', morningTime: '07:15 AM', eveningTime: '06:20 PM' },
      { id: 'mp-s2', name: 'Janakpuri District Centre Crossing', sequence: 2, campusLocation: 'Near Metro Gate 2', morningTime: '07:35 AM', eveningTime: '05:55 PM' },
      { id: 'mp-s3', name: 'Punjabi Bagh Club Road Junction', sequence: 3, campusLocation: 'Rohtak Road Underpass Bay', morningTime: '08:00 AM', eveningTime: '05:30 PM' },
      { id: 'mp-s4', name: 'Azadpur Metro Interchange', sequence: 4, campusLocation: 'Ring Road Bus Stand', morningTime: '08:25 AM', eveningTime: '05:05 PM' },
      { id: 'mp-s5', name: 'Sonipat Campus Main Terminal', sequence: 5, campusLocation: 'Academic Quadrangle Bus Bay', morningTime: '09:00 AM', eveningTime: '04:30 PM' },
    ],
    scheduledDepartures: ['07:15 AM', '04:30 PM'],
    morningSchedule: [
      { stopName: 'Manglapuri Bus Terminal (Dwarka Mor)', time: '07:15 AM', location: 'Terminal Bay 3' },
      { stopName: 'Janakpuri District Centre Crossing', time: '07:35 AM', location: 'Near Metro Gate 2' },
      { stopName: 'Punjabi Bagh Club Road Junction', time: '08:00 AM', location: 'Rohtak Road Underpass Bay' },
      { stopName: 'Azadpur Metro Interchange', time: '08:25 AM', location: 'Ring Road Bus Stand' },
      { stopName: 'Sonipat Campus Main Terminal', time: '09:00 AM', location: 'Academic Quadrangle Bus Bay (Arrival)' },
    ],
    eveningSchedule: [
      { stopName: 'Sonipat Campus Main Terminal', time: '04:30 PM', location: 'Academic Quadrangle Bus Bay (Departure)' },
      { stopName: 'Azadpur Metro Interchange', time: '05:05 PM', location: 'Ring Road Bus Stand' },
      { stopName: 'Punjabi Bagh Club Road Junction', time: '05:30 PM', location: 'Rohtak Road Underpass Bay' },
      { stopName: 'Janakpuri District Centre Crossing', time: '05:55 PM', location: 'Near Metro Gate 2' },
      { stopName: 'Manglapuri Bus Terminal', time: '06:20 PM', location: 'Terminal Bay 3 (Last Drop)' },
    ],
  },
  {
    id: 'route-panipat-sonipat',
    name: 'GT Road North: Panipat ⇄ Sonipat Campus',
    description: 'Intercity corridor connecting Panipat city, Samalkha, and Ganaur with Sonipat Campus along Grand Trunk Road (NH-44).',
    operatingDays: 'Daily (Morning & Evening Services)',
    timezone: 'IST',
    lastUpdated: '2026-10-09',
    isDemo: false,
    stops: [
      { id: 'pp-s1', name: 'Panipat Toll Plaza / Skylark Hub', sequence: 1, campusLocation: 'Main Highway Porch', morningTime: '07:00 AM', eveningTime: '06:35 PM' },
      { id: 'pp-s2', name: 'Samalkha Highway Bus Shelter', sequence: 2, campusLocation: 'Railway Crossing Junction', morningTime: '07:30 AM', eveningTime: '06:00 PM' },
      { id: 'pp-s3', name: 'Ganaur Bus Stand Stoppage', sequence: 3, campusLocation: 'GT Road Service Lane', morningTime: '08:00 AM', eveningTime: '05:30 PM' },
      { id: 'pp-s4', name: 'Murthal University Chowk', sequence: 4, campusLocation: 'Opposite Highway Dhaba Hub', morningTime: '08:30 AM', eveningTime: '05:00 PM' },
      { id: 'pp-s5', name: 'Sonipat Campus North Gate', sequence: 5, campusLocation: 'Gate 2 Transit Pavilion', morningTime: '09:00 AM', eveningTime: '04:30 PM' },
    ],
    scheduledDepartures: ['07:00 AM', '04:30 PM'],
    morningSchedule: [
      { stopName: 'Panipat Toll Plaza / Skylark Hub', time: '07:00 AM', location: 'Main Highway Porch' },
      { stopName: 'Samalkha Highway Bus Shelter', time: '07:30 AM', location: 'Railway Crossing Junction' },
      { stopName: 'Ganaur Bus Stand Stoppage', time: '08:00 AM', location: 'GT Road Service Lane' },
      { stopName: 'Murthal University Chowk', time: '08:30 AM', location: 'Opposite Highway Dhaba Hub' },
      { stopName: 'Sonipat Campus North Gate', time: '09:00 AM', location: 'Gate 2 Transit Pavilion (Arrival)' },
    ],
    eveningSchedule: [
      { stopName: 'Sonipat Campus North Gate', time: '04:30 PM', location: 'Gate 2 Transit Pavilion (Departure)' },
      { stopName: 'Murthal University Chowk', time: '05:00 PM', location: 'Opposite Highway Dhaba Hub' },
      { stopName: 'Ganaur Bus Stand Stoppage', time: '05:30 PM', location: 'GT Road Service Lane' },
      { stopName: 'Samalkha Highway Bus Shelter', time: '06:00 PM', location: 'Railway Crossing Junction' },
      { stopName: 'Panipat Toll Plaza', time: '06:35 PM', location: 'Main Highway Porch (Last Drop)' },
    ],
  },
  {
    id: 'route-rohtak-sonipat',
    name: 'Haryana West: Rohtak (Rautak) ⇄ Sonipat Campus',
    description: 'Western corridor connecting Rohtak New Bus Stand, PGIMS Medical Hub, and Kharkhoda Bypass with Sonipat Campus.',
    operatingDays: 'Monday to Saturday (Morning & Evening Services)',
    timezone: 'IST',
    lastUpdated: '2026-10-09',
    isDemo: false,
    stops: [
      { id: 'rt-s1', name: 'Rohtak New Bus Stand (Rautak Terminal)', sequence: 1, campusLocation: 'Intercity Platform #6', morningTime: '07:00 AM', eveningTime: '06:35 PM' },
      { id: 'rt-s2', name: 'Rohtak PGIMS Medical Chowk', sequence: 2, campusLocation: 'Hospital Main Gate Porch', morningTime: '07:25 AM', eveningTime: '06:05 PM' },
      { id: 'rt-s3', name: 'Kharkhoda Bypass Stoppage', sequence: 3, campusLocation: 'State Highway 18 Crossing', morningTime: '08:05 AM', eveningTime: '05:25 PM' },
      { id: 'rt-s4', name: 'Sonipat Subhash Chowk', sequence: 4, campusLocation: 'Old DC Office Circle', morningTime: '08:35 AM', eveningTime: '04:55 PM' },
      { id: 'rt-s5', name: 'Sonipat Campus Main Gate', sequence: 5, campusLocation: 'Gate 1 Reception Bay', morningTime: '09:00 AM', eveningTime: '04:30 PM' },
    ],
    scheduledDepartures: ['07:00 AM', '04:30 PM'],
    morningSchedule: [
      { stopName: 'Rohtak New Bus Stand (Rautak)', time: '07:00 AM', location: 'Intercity Platform #6' },
      { stopName: 'Rohtak PGIMS Medical Chowk', time: '07:25 AM', location: 'Hospital Main Gate Porch' },
      { stopName: 'Kharkhoda Bypass Stoppage', time: '08:05 AM', location: 'State Highway 18 Crossing' },
      { stopName: 'Sonipat Subhash Chowk', time: '08:35 AM', location: 'Old DC Office Circle' },
      { stopName: 'Sonipat Campus Main Gate', time: '09:00 AM', location: 'Gate 1 Reception Bay (Arrival)' },
    ],
    eveningSchedule: [
      { stopName: 'Sonipat Campus Main Gate', time: '04:30 PM', location: 'Gate 1 Reception Bay (Departure)' },
      { stopName: 'Sonipat Subhash Chowk', time: '04:55 PM', location: 'Old DC Office Circle' },
      { stopName: 'Kharkhoda Bypass Stoppage', time: '05:25 PM', location: 'State Highway 18 Crossing' },
      { stopName: 'Rohtak PGIMS Medical Chowk', time: '06:05 PM', location: 'Hospital Main Gate Porch' },
      { stopName: 'Rohtak New Bus Stand', time: '06:35 PM', location: 'Intercity Platform #6 (Last Drop)' },
    ],
  },
];

export const SEED_NOTICES: ServiceNotice[] = [
  {
    id: 'notice-rohini-burari',
    title: 'Rohini & Burari Route: NH-44 Stoppage Timetable',
    body: 'Morning bus arrives at campus by 9:00 AM. Evening shuttle departs campus at 4:30 PM. Please be present at designated highway shelters 5 minutes prior to scheduled departure.',
    startsAt: '2026-10-05T00:00:00Z',
    endsAt: '2026-10-25T23:59:59Z',
    routeIds: ['route-rohini-burari-sonipat'],
    isDemo: false,
  },
  {
    id: 'notice-panipat-rohtak',
    title: 'Panipat & Rohtak Corridor: Scheduled Timetable Active',
    body: 'Morning service runs 07:00 AM to 09:00 AM (campus arrival). Evening return shuttle departs at 04:30 PM. Operating Monday to Saturday.',
    startsAt: '2026-10-06T00:00:00Z',
    endsAt: '2026-10-25T23:59:59Z',
    routeIds: ['route-panipat-sonipat', 'route-rohtak-sonipat'],
    isDemo: false,
  },
];

export const SEED_REPORTS: Report[] = [
  {
    id: 'rep-001',
    referenceCode: 'CA-4912-K7',
    category: 'LIGHTING_ELECTRICAL',
    locationDescription: 'Corridor between Academic Block 2 and Central Library, near Stairwell B',
    issueDescription: 'Two overhead fluorescent fixtures are completely dark at night, leaving a 20-meter stretch of the pedestrian pathway without adequate illumination.',
    status: 'IN_PROGRESS',
    createdAt: '2026-10-07T08:15:00Z',
    updatedAt: '2026-10-07T09:45:00Z',
    auditTrail: [
      {
        id: 'aud-001-1',
        reportId: 'rep-001',
        previousStatus: 'RECEIVED',
        newStatus: 'IN_REVIEW',
        publicMessage: 'Report assigned to Estate Facilities Electrical Department for priority inspection.',
        internalNote: 'Electrical work order #E-841 assigned to technician Rajesh.',
        actorId: 'staff_vansh',
        createdAt: '2026-10-07T08:45:00Z',
      },
      {
        id: 'aud-001-2',
        reportId: 'rep-001',
        previousStatus: 'IN_REVIEW',
        newStatus: 'IN_PROGRESS',
        publicMessage: 'Electrician dispatched with replacement LED ballast and fixtures. Installation underway.',
        internalNote: 'Parts checked out from inventory; expected completion by 02:00 PM.',
        actorId: 'staff_vansh',
        createdAt: '2026-10-07T09:45:00Z',
      },
    ],
  },
  {
    id: 'rep-002',
    referenceCode: 'CA-8193-M2',
    category: 'BUILDING_FACILITY',
    locationDescription: 'Science Block 1, Ground Floor Male Restroom near Lecture Hall 101',
    issueDescription: 'Continuous water leakage from the primary sink supply line valve causing pooling water on the tiles and slip risk.',
    status: 'RECEIVED',
    createdAt: '2026-10-07T11:20:00Z',
    updatedAt: '2026-10-07T11:20:00Z',
    auditTrail: [
      {
        id: 'aud-002-1',
        reportId: 'rep-002',
        previousStatus: 'RECEIVED',
        newStatus: 'RECEIVED',
        publicMessage: 'Ticket registered in campus facilities queue.',
        internalNote: 'New automated ticket ingestion.',
        actorId: 'system',
        createdAt: '2026-10-07T11:20:00Z',
      },
    ],
  },
  {
    id: 'rep-003',
    referenceCode: 'CA-3012-P9',
    category: 'ACCESSIBILITY',
    locationDescription: 'Main Administration Building, North Entry Access Ramp',
    issueDescription: 'Handrail bolt has loosened and the anti-slip tactile strip at the base of the ramp is peeling, presenting an obstacle for wheelchair users.',
    status: 'RESOLVED',
    createdAt: '2026-10-06T14:10:00Z',
    updatedAt: '2026-10-07T07:30:00Z',
    auditTrail: [
      {
        id: 'aud-003-1',
        reportId: 'rep-003',
        previousStatus: 'RECEIVED',
        newStatus: 'IN_PROGRESS',
        publicMessage: 'Maintenance team dispatched to refit handrail anchors and replace adhesive tactile strips.',
        internalNote: 'Carpentry and safety work order #A-102.',
        actorId: 'staff_krisha',
        createdAt: '2026-10-06T15:30:00Z',
      },
      {
        id: 'aud-003-2',
        reportId: 'rep-003',
        previousStatus: 'IN_PROGRESS',
        newStatus: 'RESOLVED',
        publicMessage: 'Ramp handrail re-anchored securely with industrial hardware and new rubber tactile surface installed. Inspected and verified safe.',
        internalNote: 'Work inspected by Campus Accessibility Officer.',
        actorId: 'staff_krisha',
        createdAt: '2026-10-07T07:30:00Z',
      },
    ],
  },
];
